### ISSUE TITLE
Compare with simple-peer?

### ISSUE THREAD

**Issue by pwFoo** [chr15m/bugout#12]
Hi @chr15m,

looked into bugout and https://github.com/feross/simple-peer and try to understand the difference and additional features of bugout. 

Bugout works nice without a server (because it uses webtorrent signaling, right?) and is more secure (NaCl???). 
Bugout transfer text and could be used for chat massages seen in the demos. Simple-peer supports audio / video, it's smaller and isn't dependent on NaCl and webtorrent.

Just to unterstand what the advantages of bugout. Could you please explain? 
Obviously to me bugout do the signaling / offer / answer part for me and with simple-peer I have to do it myself (for example with a backend server to exchange offer and answer)?
But I think it's more than just that bugout is doing?

**Comment by chr15m** [comment]
@pwFoo that's correct. The main features Bugout brings which are not already present in WebTorrent and simple-peer:

 * Cryptographic pubkey based addressing & discovery of nodes.
 * RPC mechanism.

The purpose is to provide a communications channel (like simple-peer) but with 1. a deterministic way of finding peers based on their pubkeys and 2. the ability to publish and execute RPC calls.

It enables communications apps like [dirc](https://github.com/chr15m/dirc) with few lines of code.
