### ISSUE TITLE
Hard-coded trackers

### ISSUE THREAD

**Issue by draeder** [chr15m/bugout#14]
Line 37: I understand the need for hard-coded trackers in this library, but wouldn't it make more sense to enable the developer a way to specify what trackers to use? One reason might be that the user who is running the server in their browser tab may also want to be a tracker to help strengthen the imperviousness of the p2p network.

**Comment by chr15m** [comment]
Yes, the developer can specify trackers by passing a list of them in the `announce` field of the options e.g. `b = new Bugout(someroom, {announce: ["https://mytracker.net/"]})`. Please let me know if this answers your question.

**Comment by draeder** [comment]
Perfect, thank you!
