### ISSUE TITLE
Is there a way to connect to multiple rooms simultaneously?

### ISSUE THREAD

**Issue by draeder** [chr15m/bugout#15]
The idea of rooms is is brilliant and is similar to what I've done in the past with socket.io. But in that context, I would only ever create a single room for a specific purpose then all clients would connect to that single room. This seems to be similar to how your library works.

I would like a client to be able to connect to a several rooms. E.g. "Fred Flinstone" and "Roger Rabbit" at the same time. Both of these rooms would instantiated under different public identifiers so a 'many to one' connection can occur from the "server" perspective which already works grat. But I also would like to have a 'one to many' connection from the "client" perspective.

I've been reading through the unminified library code. With the current implementation, it seems that a client can only connect to one room at a time. If I'm wrong about this, and it is possible do you have any guidance on how I might accomplish it? If it's not possible, I understand.. I'll have to restructure what I'm trying to do.

**Comment by draeder** [comment]
I think I answered my own question on accident...  But if you have feedback, it would help me on my journey with javascript and your library which is absolutely brilliant.

**Comment by chr15m** [comment]
@draeder right now the way to do this is to have multiple `Bugout()` instances, one for each connection you want to make. There is not any concept of multiplexed rooms or anything like that. You would need to track an instance in every client.

**Comment by draeder** [comment]
Thanks, that's what I ended up realizing on my own on accident, but found it is (or should still be) possible. This API is amazing man. Thank you for what you created.

**Comment by chr15m** [comment]
Thank you! 🙏
