### ISSUE TITLE
Safari can not connect to more than one swarm

### ISSUE THREAD

**Issue by norzak** [chr15m/bugout#18]
Safari can not connect to more than one swarm. After the first connection to a swarm, trying to connect to other swarms resulting of creating a new swarm by itself although the same swarm is created by another browser. Firefox and Chrome do not suffer this problem.

**Comment by norzak** [comment]
Looks like you messageboard demo does not work on Safari. Could it be a Safari related problem?

**Comment by bertung** [comment]
I do not have safari 13. But it is probably working on Safari 13.
