### ISSUE TITLE
 Not working in service worker

### ISSUE THREAD

**Issue by Vladborne** [chr15m/bugout#21]
My Bugout instance does not work when I create it in Service Worker. Only the public address from the .address () call is available, but no connection socket is created. Also I do not get any errors in the console. Any ideas or is this impossible?

**Comment by chr15m** [comment]
@Vladborne unfortunately WebRTC channels that the underlying WebTorrent library use are not supported in service workers. See here for more info:

https://github.com/w3c/ServiceWorker/issues/670
https://github.com/w3c/webrtc-pc/issues/230
