### ISSUE TITLE
Uncaught join not seen - no public key.

### ISSUE THREAD

**Issue by davidaknowles** [chr15m/bugout#23]
I'm getting this error from in my client during (its first) rpc call. Is this something failing at the Webtorrent level? 

Thanks, it's a cool project!

**Comment by davidaknowles** [comment]
Ok not sure what I doing wrong honestly but I'm not getting this anymore. It wasn't reproducible so I think maybe it was something to do wit the tracker. 

In case you're interested I have a bugout-backed salad bowl (https://www.reddit.com/r/NoStupidQuestions/comments/fr9sqc/how_could_i_play_the_game_salad_bowl_online_over/) here: https://davidaknowles.github.io/saladbowl/saladbowl.html

**Comment by chr15m** [comment]
Hi @davidaknowles - looks like a cool project. This error may happen if you try to send a message before the connection occurs. You should make sure your UI makes it clear to the user when they are not yet connected and prevents them from sending messages until they are. Thanks for closing the issue!
