### ISSUE TITLE
Error ".toString() of undefined" inside .rpc()

### ISSUE THREAD

**Issue by robot45dev** [chr15m/bugout#25]
Hey. Your project is amazing. But I ran into a problem: it turns out that you can’t call callback() inside .register() if this happens inside .then() or even setTimeout(). I get the error ".toString() of undefined". I suppose there are reasons for this behavior, but it seems to me that the benefit of synchronous callback() is not much, since you cannot answer .rpc() after fetch() or a query to the database.

**Comment by chr15m** [comment]
@robot45dev thanks for reporting this. Can you provide a short piece of code to replicate the error you're seeing?

**Comment by robot45dev** [comment]
[bugout.zip](https://github.com/chr15m/bugout/files/4614322/bugout.zip)

**Comment by chr15m** [comment]
@robot45dev thank you for your patience. I have reviewed and merged the fix from @woodgern, and published `0.0.10` on npm. If you get a chance to run your use-case again please re-open this if you still have issues.
