### ISSUE TITLE
WebSocket connections to trackers blocked

### ISSUE THREAD

**Issue by robot45dev** [chr15m/bugout#27]
Everywhere I get a WebSocket connection error to 'wss: //hub.bugout.link/' or 'wss: //tracker.btorrent.xyz/' failed: Unknown reason. At first I thought that the problem was in the Live Development server, but alas, you have the same thing in the demo. Please clarify the status of the project.
![Screenshot_39](https://user-images.githubusercontent.com/62942447/84193310-e9601200-aaa3-11ea-9ce2-5dab26b77a72.png)

**Comment by chr15m** [comment]
Hello @robot45dev I am not seeing this on my local networks. Is it possible your ad blocker is preventing access to those domains? This has happened before with some ad blockers and WebTorrent. If not please verify on multiple networks to rule out a network issue.

**Comment by robot45dev** [comment]
Sorry, you're right, most ad blockers block access to trackers. In my case, AdGuard was to blame. Thank you for solving the problem.
