### ISSUE TITLE
Sessions seem to "time out" and sometimes never connect

### ISSUE THREAD

**Issue by draeder** [chr15m/bugout#28]
I've come back to bugout after a hiatus and have been playing around with basic chat. 

What I've been noticing is that the sessions are timing out if the user is idle. The other party isn't able send or receive messages in that room either because my session isn't active any longer. Sometimes the session never reconnects until the first instance is refreshed several times, or unless I duplicate the tab to "kickstart" the session. 

Is this something that you have seen before and/or do you have any ideas on how to improve connectivity? By the way, I am doing a simple p2p room, not server/client based, if that matters.

I added `b.heartbeat()` thinking it might help, but it has not.

**Comment by chr15m** [comment]
I have a long running service using Bugout which connects find even after being online for a year. I think the difference here is you want the connection itself to be long running and/or reconnect when it goes offline. I haven't tested this use-case much, but have marked this as a bug and will investigate next time I am working on Bugout. In the meantime if you discover anything please note it here. You can turn on extra debugging in the console with: `localStorage["debug"] = "bugout,webtorrent"`

Thanks for reporting this.

**Comment by draeder** [comment]
It is very likely that what I'm experiencing is OS-related as the OS tries to manage application memory.

```
bugout.min.js:11 WebSocket connection to 'wss://hub.bugout.link/' failed: Error during WebSocket handshake: Unexpected response code: 500
c @ bugout.min.js:11
_openSocket @ bugout.min.js:1
(anonymous) @ bugout.min.js:1
```

Notably, despite the above error being logged, if I send a message in one tab I still do receive the message in the other tab.  I did not have the additional tracing enabled to send over for this example. I will add WebSocket to the additional debug logging. 

Either way, I have been thinking about a Bugout server <-> bugout client approach at some point, which seems like it makes more sense for what I'm trying to do.

**Comment by chr15m** [comment]
@draeder as pointed out on #29 this could be due to that server being under load. The reason the message still goes through is there is redundancy due to two other signaling servers being used (they're not my servers but run by the WebTorrent people).

**Comment by draeder** [comment]
That does appear to be the issue. I can confirm that connections initially fail when I get a server 500 error or ERR_CONNECTION_CLOSED error from was://hub.bugout.link. Looking forward to WebRTC signaling mesh!

**Comment by chr15m** [comment]
@draeder I have upgraded the tracker server to the latest version of `bittorrent-tracker` which was long overdue. Hopefully this brings some stability.
