### ISSUE TITLE
Can we use DHT for trackerless torrents?

### ISSUE THREAD

**Issue by attish** [chr15m/bugout#33]
To achieve true decentralization, it would be nice to eliminate the need to rely on WebTorrent trackers. I tried to instantiate Bugout using `"wtOpts":{tracker:false,dht:true}`, but this way, the instances don't seem to find each other. Is this possible, even in theory? If yes, what should I do to enable it? Thanks!

**Comment by chr15m** [comment]
@attish unfortunately no it is not possible to use the DHT in an ordinary web browser as it requires sending and receiving of UDP packets.
