### ISSUE TITLE
Microsoft Edge Problem

### ISSUE THREAD

**Issue by oskrcl** [chr15m/bugout#34]
Hello everyone

There is an unknown problem in Microsoft Edge that does not allow me to use this library. Prior to this message, I have tried to find the problem but it has been impossible. Does anyone use this library in Microsoft Edge?

![imagen](https://user-images.githubusercontent.com/12387330/99081862-2cb63380-25a2-11eb-9661-46083746fe96.png)

**Comment by chr15m** [comment]
@oskrcl are there any error messages on the console? You could also turn on debugging with `localStorage["debug"]="bugout";`

**Comment by draeder** [comment]
This can probably be closed since Microsoft has abandoned its own browser development of 'Edge' in lieu of a fork of Chromium it is maintaining but still calls 'Edge'.

**Comment by chr15m** [comment]
Good idea. I should probably close a bunch of stale issues actually.

**Comment by draeder** [comment]
Closing as Edge is now Chromium based
