### ISSUE TITLE
"WebRTC: ICE failed"

### ISSUE THREAD

**Issue by ThibaultLemaire** [chr15m/bugout#35]
## Steps to reproduce:

1. Open the [demo server](https://chr15m.github.io/bugout/server.html)
2. Open a client tab in the same browser following the link given by the server

(Untested with different devices and/or different networks)

## Server log

Poorly copy-pasted from Firefox's web console.

```
https://chr15m.github.io/bugout/#bL1PrZmYMFC1xEGLrGCN2NGtHVbBbyBG6q
server.html:69:17
Connect back to this server-in-a-tab using the link above. server.html:69:17
connections: 0 server.html:69:17
Firefox can’t establish a connection to the server at wss://tracker.btorrent.xyz/. bugout.min.js:11:151595
GET wss://tracker.btorrent.xyz/
[HTTP/1.1 522  31406ms]

Firefox can’t establish a connection to the server at wss://tracker.btorrent.xyz/. bugout.min.js:11:151595
GET wss://tracker.btorrent.xyz/
[HTTP/1.1 522  31175ms]

Firefox can’t establish a connection to the server at wss://tracker.btorrent.xyz/. bugout.min.js:11:151595
GET wss://tracker.openwebtorrent.com/
[HTTP/1.1 101 Switching Protocols 115ms]

GET wss://hub.bugout.link/
[HTTP/1.1 101 Switching Protocols 539ms]

WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
GET wss://tracker.btorrent.xyz/
[HTTP/1.1 522  31039ms]

GET wss://hub.bugout.link/
[HTTP/1.1 101 Switching Protocols 531ms]

Firefox can’t establish a connection to the server at wss://tracker.btorrent.xyz/. bugout.min.js:11:151595
GET wss://tracker.openwebtorrent.com/
[HTTP/1.1 101 Switching Protocols 140ms]

WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
GET wss://hub.bugout.link/
[HTTP/1.1 101 Switching Protocols 1654ms]

GET wss://tracker.openwebtorrent.com/
[HTTP/1.1 101 Switching Protocols 118ms]

GET wss://tracker.btorrent.xyz/
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
```

I've tried to set `localStorage.debug = "bugout";` in the web console, as per the README, but to no effect. Maybe I'm not putting it in the right place?

## Additional info

I'm using Firefox on Linux.

My machine has a whitelist firewall, maybe I'm missing a port to allow? I know I had to add port 1900 for UPnP once.

I'm on my home network, so I'm behind a NAT.

---

Possibly the same issue as #32

**Comment by chr15m** [comment]
@ThibaultLemaire yes this is a common issue with restrictive firewalls and not limited to this library. I would do some searches on this phrase and see how other people are solving it:

> WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
