### ISSUE TITLE
Is this the right way to re-use a server seed in a node.js deployment?

### ISSUE THREAD

**Issue by draeder** [chr15m/bugout#38]
```
var b = Bugout({seed: "BofqDQcd9W6MNZBcU1561SPDouywe8eFdFEDDxcUmVkGiPaHtBHQ", wt: wt})
```

I am asking because I can't seem to get clients to connect this way. If I don't pass in a seed, connections work fine.

**Comment by chr15m** [comment]
@draeder yes that's how it is supposed to work, and the tests currently do that:

https://github.com/chr15m/bugout/blob/master/test.js#L26

Let me know if you have any more detail regarding how it's failing.

**Comment by draeder** [comment]
@chr15m I was using your node.js example from [here](https://github.com/chr15m/bugout/blob/master/docs/examples/node/main.js), and tried starting a new instance by passing in the previous seed. 

No errors were logged, but I didn't have debugging turned on. I can do that later on when I have a chance to circle back to it. If you want to close this issue for now, I can open a new one on this when I have some time to test with debugging turned on.

**Comment by chr15m** [comment]
@draeder understood. Let's leave this issue open for now.

**Comment by draeder** [comment]
@chr15m Sure, no problem... 

As a note: I've been playing with P2PT also which works in a similar way to Bugout using WebTorrent/DHT. I seem to be able to get clients connected more reliably with that library. I've wondered if the issue is with the trackers, so I passed in the same trackers P2PT uses to Bugout but still had the same issues. Note: all of my testing is local at the moment. For what I'm working on, I'm using hyperswarm, P2PT, and Bugout.. I'm sure there is redundancy between those three libraries, but I'm not skilled enough yet to consolidate them.

**Comment by draeder** [comment]
I'm not quite sure how to debug in node.js, since `localstorage["debug"] = "bugout"` only works in the browser.

**Comment by chr15m** [comment]
@draeder you should be able to set debug logging with an environment variable: `DEBUG=bugout node myserver.js`.

Are you initializing WebTorrent with a `webrtc` instance like this: https://github.com/chr15m/bugout/blob/master/docs/examples/node/main.js#L5

**Comment by draeder** [comment]
Thanks - I will give that a try. Yes - that's how I'm initializing WebTorrent. 

By the way, I just set up a local signaling server and I'm getting much better results. This tells me the issue I've been experiencing has really been with responsiveness of signaling servers.

I had an idea for how to create a WebRTC signaling mesh, which I remember you mentioning on another issue. The basic idea would be an npm package that uses [hyperswarm](https://github.com/hyperswarm/hyperswarm/blob/master/swarm.js) to dynamically connect servers to a static topic, say: 'bugout-signaling-mesh'. It would also run a local signaling server on a given port, which would require some port forwarding at the router (unless there's a way to punch through). That signalling server's public IP and port would then be shared between the other connected servers. Bugout could then be configured to re-announce its WebTorrent to that list of trackers, and any new connections to the Bugout address would start seeding on that tracker list.

**Comment by chr15m** [comment]
That sounds good. I've been working on this, which operates at the webrtc layer.

https://github.com/chr15m/webrtc-signaling-mesh

Let me know if you have any feedback.

**Comment by chr15m** [comment]
> Is there a way to update trackers an instance of Bugout uses after initialization?

I am not sure but I imagine it's possible to update this on the torrent object inside Bugout. Would need to test.

**Comment by draeder** [comment]
The [hypercore protocol](https://hypercore-protocol.org) seems to be trying to solve a lot of decentralization problems, but I haven't had a chance to really experiment with it much beyond hyperswarm which I've had success with. Hypercore is looking like a competitor to IPFS (which is extremely confusing to me).

Hyperswarm, a component of hypercore, uses DHT/WebTorrent, with fallbacks to LSD (localhost), UTP/UDP, which makes it pretty universal as a way to connect node servers. But it fails at the browser level -- it can't be browserified from what I can tell. If you plan to make your mesh server-oriented, hyperswarm is very good for server <-> server connections.

The PoW concept for your webrtc-signalling-mesh is a great idea. There should be some kind of network latency measurement that is calculated, too. But that measurement would be relative to peers who need that given tracker, so possibly geolocation / or just a ping test to the tracker id's and pick the ones with the lowest latency + lowest PoW. 

I'm going to work on my concept still, but it seems like yours will ultimately be better 👍. 

One thing I really struggle with is how to re-use sockets/data-channels from a given library like Bugout or Hyperswarm.

**Comment by chr15m** [comment]
@draeder thanks for the tip on hyperswarm, looks great.

**Comment by draeder** [comment]
@chr15m I created a tracker server that should be reliable: wss://ws.peer.ooo. You're welcome to use it if you'd like. It's deployed as an app in Heroku. If others want to deploy their own, they can do so here: https://github.com/draeder/p2p-tracker
