### ISSUE TITLE
"Novage/wt-tracker" does not work with multiple instances of Bugout()

### ISSUE THREAD

**Issue by KRAdev** [chr15m/bugout#40]
Hey! I have a problem. When creating multiple instances of Bugout () in one browser tab, everything works fine only if I connect to your tracker "wss: //hub.bugout.link" or "wss: //tracker.openwebtorrent.com". But if I build my tracker locally from https://github.com/Novage/wt-tracker, then no instance of Bugout () works. There are no errors either on the client or on the tracker. Have you encountered this behavior? I guess this is a problem in the tracker, but I don't know how to fix it. Can you tell which tracker is installed on your server?

**Comment by chr15m** [comment]
@KRAdev this one: https://github.com/webtorrent/bittorrent-tracker
