### ISSUE TITLE
Data transmission not working

### ISSUE THREAD

**Issue by tanayseven** [chr15m/bugout#44]
I tried a lot of things and a lot of combinations.
[playindoor.games](https://github.com/tanayseven/playindoor.games)

Nothing seems to be working, I'm thinking to move away from using `bugout` now.
Requesting some help from you, if possible before I decide to move away.

**Comment by chr15m** [comment]
Hi @tanayseven. The best way to get help is to provide details about the problems or bugs you are experiencing. If a specific bug can be replicated then it can be fixed. Nobody can do much with a statement like "nothing seems to be working".

If this library with its default trackers is not a stable enough basis for your app's networking here are some alternatives:

 * Run your own tracker server. The volunteer run servers that Bugout uses are often overloaded.
 * Try an alternative peer-to-peer library like peer.js or P2PT.
 * Use a less cutting-edge approach with a centralized server using websockets or SSE.

Best of luck.
