### ISSUE TITLE
How does bugout work?

### ISSUE THREAD

**Issue by hello-smile6** [chr15m/bugout#52]
I want to make a P2P networking adapter for https://github.com/copy/v86 by @copy , how would that work?

**Comment by chr15m** [comment]
Sounds like a fun project. If you get it working let me know and I'll add a link to the README.

**Comment by hello-smile6** [comment]
> Sounds like a fun project. If you get it working let me know and I'll add a link to the README.

But how would I make it work?

**Comment by chr15m** [comment]
I do not know.

**Comment by hello-smile6** [comment]
> I do not know.

How do I load Bugout? Once I get that, I can just use a tool I created and figure out how it works.
