### ISSUE TITLE
Remote access via bugout

### ISSUE THREAD

**Issue by hello-smile6** [chr15m/bugout#56]
I often want to use v86 on low-end devices (such as phones with only 512 MB (or less) of RAM. I just realized that I could remotely access a VM on a better device via bugout! Thanks for making bugout, it's amazing.

**Comment by draeder** [comment]
v86 is pretty cool man! Thanks for sharing it. Do you have any more info on how you're using Bugout to access?

**Comment by hello-smile6** [comment]
> [v86](https://github.com/copy/v86) is pretty cool man! Thanks for sharing it. Do you have any more info on how you're using Bugout to access?

Actually, I was hoping you could create a relay script that allows at least serial access remotely, if not full CLI access.

**Comment by draeder** [comment]
That is probably a question for [v86](https://github.com/copy/v86). As I was looking at it and its issues, I saw others have asked about networking and peer-to-peer networking access. It isn't exactly trivial to accomplish.

What are you trying to do? How would Bugout help?

**Comment by hello-smile6** [comment]
> That is probably a question for [v86](https://github.com/copy/v86). As I was looking at it and its issues, I saw others have asked about networking and peer-to-peer networking access. It isn't exactly trivial to accomplish.
> 
> What are you trying to do? How would Bugout help?

I'm trying to create a configuration which would allow me to remotely use a v86 VM running on a web browser.

**Comment by hello-smile6** [comment]
> See: [copy/v86#569](https://github.com/copy/v86/issues/569), and [s-macke/jor1k#154](https://github.com/s-macke/jor1k/issues/154). Neither of these are really a Bugout issue... That said, you _can_ access v86 VMs running in a web browser. See these [demos](https://github.com/copy/v86#demos). All of them are running in your browser as far as I understand.
> 
> This issue should be closed, as it's not really Bugout related.

I was just hoping you could help me with using Bugout for sending data.

**Comment by draeder** [comment]
@hello-smile6 What issue are you having with using Bugout for sending data? As long as I have a reliable tracker server, I have no issues.

**Comment by hello-smile6** [comment]
> @hello-smile6 What issue are you having with using Bugout for sending data? As long as I have a reliable tracker server, I have no issues.

I just haven't figured out how to send the contents of the serial terminal via Bugout yet.

**Comment by hello-smile6** [comment]
@chr15m Would https://github.com/copy/v86/issues/172#issuecomment-395253645 maybe work?

**Comment by hello-smile6** [comment]
> @hello-smile6 What issue are you having with using Bugout for sending data? As long as I have a reliable tracker server, I have no issues.

Would https://github.com/copy/v86/issues/172#issuecomment-395253645 work?

**Comment by draeder** [comment]
@hello-smile6 I don't think this is a Bugout issue or question.

**Comment by hello-smile6** [comment]
> @hello-smile6 I don't think this is a Bugout issue or question.

Okay, I'm just trying to figure it out.

**Comment by hello-smile6** [comment]
@draeder I got it to work!
# Server
![image](https://user-images.githubusercontent.com/73048226/148630044-7683eb40-12ba-441c-b59e-bd5a07219564.png)
# Client
![image](https://user-images.githubusercontent.com/73048226/148630054-51e1b675-6e80-408c-800e-9850e3cd507a.png)
Now, just have to get input working.

**Comment by hello-smile6** [comment]
@draeder @copy Got it!

https://user-images.githubusercontent.com/73048226/148630248-42ad3ea7-cb1f-4a6c-833d-541bbdc12025.mp4

<a href="https://github.com/hello-smile6/libv86-terminal-forwarding"><code>hello-smile6/libv86-terminal-forwarding</code></a>

**Comment by draeder** [comment]
@hello-smile6 That's great! Interesting project.. I starred it so I can follow updates. Closing this one out.
