### ISSUE TITLE
How do I RPC a client in a P2P room?

### ISSUE THREAD

**Issue by hello-smile6** [chr15m/bugout#57]
I am making a P2P social media app and want to use RPC calls to retrieve data. Should I connect to the peer address, or is there another way?

**Comment by hello-smile6** [comment]
I'll just pass a WebTorrent() instance to all of my Bugout instances.

**Comment by draeder** [comment]
Register your RPC:

```js
  b.register("ping", function(address, args, cb) {
    args["pong"] = Math.random(); // this is the RPC action
    cb(args);
  });
```

Create a listener for your RPC:
```js
  b.on("rpc", function(address, call, args) { 
    console.log("rpc:", address, call, args);
  });
```
