### ISSUE TITLE
[question] Maturity state

### ISSUE THREAD

**Issue by jarodium** [chr15m/bugout#60]
Hello

I would like to know if bugout is mature enough to deploy to production server, or if it's still a much "work with it at your own risk" kind of thing, as stated in this repo page.

I would like very much to use it with a tech support module i'm building into my CMS, among other applications, so I will pretty much use it on a VPS as a server and launch this support tabs from the CMS.

Best regards

**Comment by chr15m** [comment]
@jarodium if you are building a tech support module on an existing site I would use websockets or SSE.

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events

Bugout works best in the situation where you don't have an existing website backend or webserver as it allows for communication directly between peers.
