### ISSUE TITLE
[REQUEST] Can you make your tracker source code available?

### ISSUE THREAD

**Issue by norzak** [chr15m/bugout#65]
Can you make your webtorrent tracker source code available?

**Comment by JohnnySheffield** [comment]
I presume the bugout tracker is made from this repo; https://github.com/webtorrent/bittorrent-tracker but additional info or open-sourcing it would be helpful!

**Comment by chr15m** [comment]
@norzak It's simply running [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker). Maybe it's time to refresh all the libraries etc. You can try excluding `hub.bugout.link` from the server list to see if that's the problem.

**Comment by norzak** [comment]
@chr15m no hub.bugout.link is not the problem. I presume the other two public trackers do not keep connections open for seeding. Refreshing page 3-4 times, it starts to work indicating that trackers are not reliable. Thanks got a tracker now, I will see if it is going to work with a private tracker and go from there.

**Comment by norzak** [comment]
I can confirm that all works well with a private tracker.

**Comment by draeder** [comment]
@norzak You can use mine.. It shouldn't be too overloaded (yet): [wss://tracker.peer.ooo/](https://tracker.peer.ooo/)
