### ISSUE TITLE
Build is broken with WebTorrent 2.x.x

### ISSUE THREAD

**Issue by bertung** [chr15m/bugout#68]
Build is broken with WebTorrent 2.x.x version which is significantly faster and smaller than the 1.9.x branch. It seems like es6 style imports are expected. There is "terser" for minification, but browserify needs babelify I guess which I haven't used before.

**Comment by chr15m** [comment]
Ok, thanks for the heads up!

**Comment by bertung** [comment]
It is possible to supply web torrent externally using

browserify -s Bugout --external webtorrent index.js > bugout.js

**Comment by chr15m** [comment]
What should the solution be here do you think? Upgrade Bugout to use es6 style imports?

**Comment by bertung** [comment]
I think problem is with the webtorrent browserify trying to embed to the final executable. New versions of web torrent uses es6 style imports. If you exclude webtorrent, compilation by browserify succeeds.  I am not a npm expert but, it may also be related to only using imports throughout out the entire code. The initial solution without messing with the bugout code would be externally supplying the webtorrent client which is offered in options of bugout.

**Comment by bertung** [comment]
You may close this issue since there is a workaround.

**Comment by draeder** [comment]
Closing since there is a workaround
