### ISSUE TITLE
Bugout instance name instead of address

### ISSUE THREAD

**Issue by robert1233** [chr15m/bugout#8]
Is there a way to say "Robert connected", instead of using the hash address?
Thanks!

**Comment by chr15m** [comment]
Yes there are different ways to associate a name with a hash and it really depends on your design choices. Some ways to do it:

 * Have the user specify their own user name and send a packet out to each new Bugout instance that there is a `seen` event for telling them what username to use. This is the method used by [dirc](https://github.com/chr15m/dirc) - if you don't mind multiple users potentially having the same username on the screen then this method is fine.

 * Link user names to some external service like Twitter or GitHub. This is what gitter.im does for example. In a post called [decentralized identity linking](https://chr15m.github.io/decentralized-identity-linking.html) I wrote up some ideas around that concept.

 * Build your own username registration infrastructure.

At the lowest level what you want is for the message recipient's Bugout node to have some concept of a username associated with the hash. A simple key->value mapping from hash->username can solve this but what goes into the value side of the lookup and how it gets there depends upon your design.
